# SVM MULTICLASS ASPEK

In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel(r"C:\Users\user\Documents\cnn_aspek.xlsx")
df

opini        kategori
0                                  berita cepat terkini  content_berita
1                                     tarik berita baru  content_berita
2                              berita bagus sesuai jadi  content_berita
3                                        aplikasi henti   functionality
4     berita terkini mantap percaya maju cnn indones...  content_berita
...                                                 ...             ...
1995                          berita buruk tidak netral  content_berita
1996                             aplikasi nyaman lancar   functionality
1997                           berita sangat independen  content_berita
1998                           tema bagus tidak bingung      navigation
1999                               iklan sedikit mantap   content_iklan

[2000 rows x 2 columns]

In [2]:
df['kategori'].value_counts() #untuk melihat berapa jumlah setiap label

content_berita           1530
functionality             359
content_iklan              58
navigation                 23
video / audio quality      15
interactivity              15
Name: kategori, dtype: int64

In [3]:
print(len(df)) #data sebanyak 2500 karena dimulai dari 0 maka 2499

2000


In [4]:
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer
vectorizer = CountVectorizer(decode_error="replace")
transformer = TfidfTransformer()
TFIDF = transformer.fit_transform(vectorizer.fit_transform(df['opini']))

In [5]:
print(TFIDF)

  (0, 2225)	0.5992105580891981
  (0, 407)	0.7485234565402487
  (0, 268)	0.2840058838888207
  (1, 2174)	0.7033408561977688
  (1, 268)	0.22614009010338812
  (1, 220)	0.6739230665669644
  (2, 2046)	0.579752865399638
  (2, 909)	0.7181389848717513
  (2, 268)	0.17627675953514355
  (2, 167)	0.3421834559356558
  (3, 782)	0.9067925101938833
  (3, 119)	0.42157720936535004
  (4, 2225)	0.254790849638393
  (4, 1718)	0.2991038423787417
  (4, 1302)	0.6747946485083484
  (4, 1269)	0.47957836362844825
  (4, 849)	0.2997155146865626
  (4, 442)	0.23635216261372047
  (4, 268)	0.12076239225338155
  (5, 2225)	0.37955215941939124
  (5, 1718)	0.44556352563919605
  (5, 1490)	0.5040780625400612
  (5, 820)	0.5304459263534499
  (5, 167)	0.349207286551892
  (6, 1585)	0.9736029334780484
  :	:
  (1992, 9)	0.48899076573752565
  (1993, 849)	0.522437648187127
  (1993, 759)	0.8262854617900552
  (1993, 268)	0.2105023500845036
  (1994, 2290)	0.45172330562705787
  (1994, 2269)	0.48532141118074146
  (1994, 2189)	0.60867739720

In [6]:
#Save model TFIDF
import pickle
pickle.dump(vectorizer.vocabulary_,open("TFIDF.pkl","wb")) #simpan ke pickle

In [7]:
labels = [] #membuat kolom labels
for data in df['kategori']:#untuk data di df row kategori
    labels.append(data)
kolom = labels.pop
print(labels)

['content_berita', 'content_berita', 'content_berita', 'functionality', 'content_berita', 'content_iklan', 'content_berita', 'content_berita', 'functionality', 'content_berita', 'navigation', 'content_berita', 'functionality', 'functionality', 'content_berita', 'content_berita', 'functionality', 'video / audio quality', 'content_berita', 'content_berita', 'content_berita', 'content_berita', 'content_berita', 'content_berita', 'content_berita', 'content_berita', 'content_berita', 'video / audio quality', 'content_iklan', 'content_berita', 'functionality', 'content_berita', 'content_berita', 'content_berita', 'content_iklan', 'content_berita', 'content_berita', 'content_berita', 'functionality', 'functionality', 'content_berita', 'content_berita', 'content_berita', 'functionality', 'content_berita', 'content_berita', 'content_berita', 'functionality', 'content_berita', 'video / audio quality', 'content_berita', 'content_berita', 'content_berita', 'content_berita', 'content_berita', 'cont

In [10]:
#kemudian kategori diberi label
label=[]
for i in range(len(labels)): 
    if labels[i]=='content_berita':
        nilai = 0
        label.append(nilai)
    
    if labels[i]=='functionality':
        nilai = 1
        label.append(nilai)
    
    if labels[i]=='content_iklan':
        nilai = 2
        label.append(nilai)
        
    if labels[i]=='navigation':
        nilai = 3
        label.append(nilai)
        
    if labels[i]=='interactivity':
        nilai = 4
        label.append(nilai)
        
    if labels[i]=='video / audio quality':
        nilai = 5
        label.append(nilai)
    

In [11]:
print(len(label))
print(len(df))
print(label)

2000
2000
[0, 0, 0, 1, 0, 2, 0, 0, 1, 0, 3, 0, 1, 1, 0, 0, 1, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 2, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 2, 3, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 2, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 4, 1, 0, 0, 2, 2, 0, 0, 5, 0, 1, 1, 0, 0, 0, 1, 1, 0, 4, 0, 0, 0, 3, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 3, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 0, 2, 3, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 5, 0, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 3, 0, 2, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 3, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,

In [12]:
from sklearn import svm #metode untuk klasifikasi aspek / kategori
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer #untuk menghitung vsm dan tfidf #vsm =vector space model
from sklearn import metrics #metode untuk pembentukan matriks 1x1 1x2 1x3
from sklearn.metrics import accuracy_score #metod untuk pembentukan skor akurasi 
from sklearn.model_selection import KFold #metode untuk perhitungan kfold
import numpy as np 
import re #regular expression
import itertools #fungsi pengulangan tak terbatas
import matplotlib.pyplot as plt #pembentukan diagram
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC #suport vector classifier
from sklearn.metrics import classification_report

In [13]:
print(label)

[0, 0, 0, 1, 0, 2, 0, 0, 1, 0, 3, 0, 1, 1, 0, 0, 1, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 2, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 2, 3, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 2, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 4, 1, 0, 0, 2, 2, 0, 0, 5, 0, 1, 1, 0, 0, 0, 1, 1, 0, 4, 0, 0, 0, 3, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 3, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 0, 2, 3, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 5, 0, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 3, 0, 2, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 3, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 

In [14]:
#METHOD MENGHITUNG RATA2 AKURASI#
akurasi = []
akurasi1 = []
akurasi2 = []
akurasi3 = []
def avg_akurasiLinear(): ## nama fungsi
    total = 0 ## pengosongan variabel
    for i in range(10): ## looping 10x karena ada 10 fold
        total = total + akurasi[i] ## tiap looping nilai total akan ditambahkan dengan nilai akurasi tiap fold
    print("------------------------------------------------------------") 
    print("Rata-rata akurasi keseluruhan SVM LinearSVC adalah :", total / 10) ## cetak rata-rata akurasi
def avg_akurasiSVM(): ## nama fungsi
    total = 0 ## pengosongan variabel
    for i in range(10): ## looping 10x karena ada 10 fold
        total = total + akurasi1[i] ## tiap looping nilai total akan ditambahkan dengan nilai akurasi tiap fold
    print("Rata-rata akurasi keseluruhan SVM kernel Linear adalah :", total / 10) ## cetak rata-rata akurasi
def avg_akurasiPolynomial(): ## nama fungsi
    total = 0 ## pengosongan variabel
    for i in range(10): ## looping 10x karena ada 10 fold
        total = total + akurasi2[i] ## tiap looping nilai total akan ditambahkan dengan nilai akurasi tiap fold
    print("Rata-rata akurasi keseluruhan SVM kernel Polynomial adalah :", total / 10) ## cetak rata-rata akurasi
def avg_akurasiRBF(): ## nama fungsi
    total = 0 ## pengosongan variabel
    for i in range(10): ## looping 10x karena ada 10 fold
        total = total + akurasi3[i] ## tiap looping nilai total akan ditambahkan dengan nilai akurasi tiap fold
    print("Rata-rata akurasi keseluruhan SVM kernel RBF adalah :", total / 10) ## cetak rata-rata akurasi

In [16]:
kFoldCrossValidation = KFold(n_splits=10)#fungsi K-Fold Cross Validation melakukan insialisasi 10 kali iterasi
for latih, uji in kFoldCrossValidation.split(TFIDF, label):#proses looping yg masing2 pernah jadi data latih maupun uji
    
    print("-----------------------------")
    print("Banyak Data Latih: ", len(latih)) #berapa jmlah data latih
    print("Banyak Data Uji: ", len(uji)) #berapa jumlah data uji
    print("\nData Latih: \n", latih) #menampilkan data latih
    print("\nData Uji: \n", uji)#menampilkan data uji
    
    dataLatih1, dataUji1 = TFIDF[latih], TFIDF[uji]#proses inisialisasi dari masing2 data latih/uji dijadikan nilai tfidf lalu di copy ke variabel dataLatih/Uji1
    label = np.array(label)
    dataLatih2, dataUji2 = label[latih], label[uji]#proses inisialisasi dari masing2 data latih/uji dibentuk ke label untuk proses prediksi lalu di copy ke variabel dataLatih/Uji2

    SVMLinear = svm.LinearSVC()
    modelLinear = SVMLinear.fit(dataLatih1, dataLatih2)#data latih melakukan proses pelatihan dengan algoritma SVM
    prediksi = modelLinear.predict(dataUji1)#proses prediksi dari data latih yang sudah tersimpan sebagai model
    
    SVM = svm.SVC(kernel='linear')
    modelSVM = SVM.fit(dataLatih1, dataLatih2)  # data latih melakukan proses pelatihan dengan algoritma SVM
    prediksi1 = modelSVM.predict(dataUji1)  # proses prediksi dari data latih yang sudah tersimpan sebagai model
    
    SVMPoly = svm.SVC(kernel='poly', degree=3)
    modelPoly = SVMPoly.fit(dataLatih1, dataLatih2)  # data latih melakukan proses pelatihan dengan algoritma SVM
    prediksi2 = modelPoly.predict(dataUji1)  # proses prediksi dari data latih yang sudah tersimpan sebagai model
    
    SVMRBF = svm.SVC(kernel='rbf', gamma=0.7)
    modelRBF = SVMRBF.fit(dataLatih1, dataLatih2)  # data latih melakukan proses pelatihan dengan algoritma SVM
    prediksi3 = modelRBF.predict(dataUji1)  # proses prediksi dari data latih yang sudah tersimpan sebagai model

    print("\nHasil Prediksi SVM RBF: \n", prediksi3)
    #membuat confussion matrix
    
    print("\nConfusion Matrix: \n", metrics.confusion_matrix(dataUji2, prediksi1))

    akurasi.append(accuracy_score(dataUji2, prediksi))
    akurasi1.append(accuracy_score(dataUji2, prediksi1))
    akurasi2.append(accuracy_score(dataUji2, prediksi2))
    akurasi3.append(accuracy_score(dataUji2, prediksi3))

    print("\nAkurasi SVM kernel RBF: ", accuracy_score(dataUji2, prediksi3))
    print()\

    label_target = ['class 0(content_berita)','class 1 (functionality)','class 2 (content_iklan)','class 3 (interactivity)','class 4 (navigation)','class 5 (video / audio quality)'] #berikut merupakan label target
    
    print(metrics.classification_report(dataUji2, prediksi1,labels=[0,1,2,3,4,5])) #memberikan kelas label karena model hanya memprediksi 4 kelas
    #yang menyebabkan kesalahan matriks kebingungan

avg_akurasiRBF() #hitung rata rata kernel rbf

-----------------------------
Banyak Data Latih:  1800
Banyak Data Uji:  200

Data Latih: 
 [ 200  201  202 ... 1997 1998 1999]

Data Uji: 
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199]

Hasil Prediksi SVM RBF: 
 [0 0 0 1 0 2 0 0 1 

C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



Hasil Prediksi SVM RBF: 
 [2 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 2
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1
 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]

Confusion Matrix: 
 [[153   3   1   0   0   0]
 [ 15   9   0   0   0   0]
 [  2   0   6   0   0   0]
 [  7   1   0   0   0   0]
 [  1   0   0   0   0   0]
 [  1   1   0   0   0   0]]

Akurasi SVM kernel RBF:  0.84

              precision    recall  f1-score   support

           0       0.85      0.97      0.91       157
           1       0.64      0.38      0.47        24
           2       0.86      0.75      0.80         8
           3       0.00      0.00      0.00         8
           4       0.00      0.00      0.00         1
           5       0.00  

C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



Hasil Prediksi SVM RBF: 
 [1 1 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 2 2 0 0 2 0 0 0 0 0 0 0 0 0 0
 0 0 0 2 0 0 0 1 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 1 0 1 0 1 0 0 0 0
 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 2 0 0 0 1 0 0 1 0 2 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 2 0 0 0 0 0 1 0 1 0]

Confusion Matrix: 
 [[131   6   0   0   0   0]
 [ 13  29   0   0   0   0]
 [  0   0  10   0   0   0]
 [  3   0   0   1   0   0]
 [  1   0   0   0   0   0]
 [  5   1   0   0   0   0]]

Akurasi SVM kernel RBF:  0.825

              precision    recall  f1-score   support

           0       0.86      0.96      0.90       137
           1       0.81      0.69      0.74        42
           2       1.00      1.00      1.00        10
           3       1.00      0.25      0.40         4
           4       0.00      0.00      0.00         1
           5       0.00 

C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



Hasil Prediksi SVM RBF: 
 [2 1 0 0 0 0 0 0 0 0 2 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 2 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]

Confusion Matrix: 
 [[148   3   2   0   0]
 [ 23  14   0   0   0]
 [  1   0   6   0   0]
 [  1   1   0   0   0]
 [  1   0   0   0   0]]

Akurasi SVM kernel RBF:  0.83

              precision    recall  f1-score   support

           0       0.85      0.97      0.91       153
           1       0.78      0.38      0.51        37
           2       0.75      0.86      0.80         7
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         2
           5       0.00      0.00      0.00         1

   micro avg     

C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\


Hasil Prediksi SVM RBF: 
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

Confusion Matrix: 
 [[163   0   0]
 [ 29   7   0]
 [  1   0   0]]

Akurasi SVM kernel RBF:  0.84

              precision    recall  f1-score   support

           0       0.84      1.00      0.92       163
           1       1.00      0.19      0.33        36
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         0

   micro avg       0.85      0.85      0.85       200
   macro avg       0.31      0.20

C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\


Hasil Prediksi SVM RBF: 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 2 1 0 0 0 2 0 0 0 0 0 0 0 0 0
 0 2 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0
 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

Confusion Matrix: 
 [[155   5   1   0   1]
 [ 19  12   0   0   0]
 [  0   0   5   0   0]
 [  1   0   0   1   0]
 [  0   0   0   0   0]]

Akurasi SVM kernel RBF:  0.85

              precision    recall  f1-score   support

           0       0.89      0.96      0.92       162
           1       0.71      0.39      0.50        31
           2       0.83      1.00      0.91         5
           3       0.00      0.00      0.00         0
           4       1.00      0.50      0.67         2
           5       0.00      0.00      0.00         0

   micro avg     

C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\


Hasil Prediksi SVM RBF: 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

Confusion Matrix: 
 [[153   2   1   0   0]
 [ 24  16   0   0   0]
 [  0   0   1   0   0]
 [  2   0   0   0   0]
 [  1   0   0   0   0]]

Akurasi SVM kernel RBF:  0.83

              precision    recall  f1-score   support

           0       0.85      0.98      0.91       156
           1       0.89      0.40      0.55        40
           2       0.50      1.00      0.67         1
           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         0

   micro avg     

C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\


Hasil Prediksi SVM RBF: 
 [0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2
 0 0 0 0 0 1 0 0 0 0 0 2 0 0 0 0 0 2 0 0 0 2 2 0 2 2 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]

Confusion Matrix: 
 [[156   9   1   0   0]
 [ 15   6   0   0   0]
 [  1   0   8   0   0]
 [  1   1   0   0   0]
 [  2   0   0   0   0]]

Akurasi SVM kernel RBF:  0.855

              precision    recall  f1-score   support

           0       0.89      0.94      0.91       166
           1       0.38      0.29      0.32        21
           2       0.89      0.89      0.89         9
           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         2
           5       0.00      0.00      0.00         0

   micro avg    

C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\


Hasil Prediksi SVM RBF: 
 [0 1 2 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 2 0 0 0 0 0
 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1]

Confusion Matrix: 
 [[143  10   0   0]
 [ 21  21   0   0]
 [  0   0   3   0]
 [  0   1   1   0]]

Akurasi SVM kernel RBF:  0.82

              precision    recall  f1-score   support

           0       0.87      0.93      0.90       153
           1       0.66      0.50      0.57        42
           2       0.75      1.00      0.86         3
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         2
           5       0.00      0.00      0.00         0

   micro avg       0.83      0.83      0.83       200
  

C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\


Hasil Prediksi SVM RBF: 
 [0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 2 0 0 2 0 0 0
 0 0 0 0 0 1 0 0 0 0 2 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1
 0 1 0 0 0 0 0 1 0 1 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 2]

Confusion Matrix: 
 [[139  10   1   0   0]
 [ 18  22   0   0   0]
 [  1   0   5   0   0]
 [  3   0   0   0   0]
 [  0   0   0   0   1]]

Akurasi SVM kernel RBF:  0.81

              precision    recall  f1-score   support

           0       0.86      0.93      0.89       150
           1       0.69      0.55      0.61        40
           2       0.83      0.83      0.83         6
           3       0.00      0.00      0.00         3
           4       1.00      1.00      1.00         1
           5       0.00      0.00      0.00         0

   micro avg     

C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\

In [17]:
# save the model to disk
import pickle
filename = 'SVMLinier_model.sav'
pickle.dump(SVMLinear, open(filename, 'wb'))

In [18]:
# save the model to disk
import pickle
filename = 'SVM_model.sav'
pickle.dump(SVM, open(filename, 'wb'))

In [19]:
# save the model to disk
import pickle
filename = 'SVMPolynomial_model.sav'
pickle.dump(SVMPoly, open(filename, 'wb'))

In [20]:
# save the model to disk
import pickle
filename = 'SVMRBF_model.sav'
pickle.dump(SVMRBF, open(filename, 'wb'))

In [21]:
# save the model to disk
import pickle
filename = 'TFIDF.pickle'
pickle.dump(TFIDF, open(filename, 'wb'))

# LOAD MODEL

In [22]:
import string
import Sastrawi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

In [23]:
kalimat = "Berita online CNN ini sangat bagus, namun iklannya sangat mengganggu tolong diperbaiki" 
lower_case = kalimat.lower()
print (lower_case)

berita online cnn ini sangat bagus, namun iklannya sangat mengganggu tolong diperbaiki


In [24]:
punctuation = lower_case.translate(str.maketrans('','',string.punctuation)).strip()
print(punctuation)

berita online cnn ini sangat bagus namun iklannya sangat mengganggu tolong diperbaiki


In [25]:
tokenize = word_tokenize(punctuation)
print(tokenize)

['berita', 'online', 'cnn', 'ini', 'sangat', 'bagus', 'namun', 'iklannya', 'sangat', 'mengganggu', 'tolong', 'diperbaiki']


In [26]:
factory = StopWordRemoverFactory()
stopword = factory.create_stop_word_remover()
hasil_stopword = []
for i in tokenize:
    word = stopword.remove(i)
    if word !='':
        hasil_stopword.append(word)
print(hasil_stopword)

['berita', 'online', 'cnn', 'sangat', 'bagus', 'iklannya', 'sangat', 'mengganggu', 'diperbaiki']


In [27]:
factory = StemmerFactory()
stemmer = factory.create_stemmer()  
hasil_stemming = [] 
for i in hasil_stopword:
    word = stemmer.stem(i)
    if word !='':
        hasil_stemming.append(word) 
print(hasil_stemming)

['berita', 'online', 'cnn', 'sangat', 'bagus', 'iklan', 'sangat', 'ganggu', 'baik']


In [28]:
teks_ulasan=[' '.join(reversed(hasil_stemming))]
print(teks_ulasan)

['baik ganggu sangat iklan bagus sangat cnn online berita']


In [29]:
#Load TFIDF model
import pickle
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer
transformer = TfidfTransformer()
loaded_vec = CountVectorizer(decode_error="replace",vocabulary=pickle.load(open("TFIDF.pkl", "rb")))
tfidf = transformer.fit_transform(loaded_vec.fit_transform(teks_ulasan))

In [30]:
print (tfidf)

  (0, 1937)	0.6030226891555273
  (0, 1607)	0.30151134457776363
  (0, 820)	0.30151134457776363
  (0, 678)	0.30151134457776363
  (0, 442)	0.30151134457776363
  (0, 268)	0.30151134457776363
  (0, 185)	0.30151134457776363
  (0, 167)	0.30151134457776363


In [31]:
loaded_SVM_model = pickle.load(open('SVM_model.sav', 'rb'))

In [32]:
print (loaded_SVM_model)

SVC(kernel='linear')


In [33]:
loaded_SVM_model.predict(tfidf)

array([2])

In [34]:
# load SVM  LINIER model
loaded_SVMlinier_model = pickle.load(open('SVMLinier_model.sav', 'rb'))

In [35]:
print (loaded_SVMlinier_model)

LinearSVC()


In [36]:
loaded_SVMlinier_model.predict(tfidf)

array([2])

In [37]:
# load SVM  POLYNOMIAL model
loaded_SVMpolynomial_model = pickle.load(open('SVMPolynomial_model.sav', 'rb'))

In [38]:
print (loaded_SVMpolynomial_model)

SVC(kernel='poly')


In [39]:
loaded_SVMpolynomial_model.predict(tfidf)

array([0])

In [40]:
# load SVM RBF model
loaded_SVMrbf_model = pickle.load(open('SVMRBF_model.sav', 'rb'))

In [41]:
print (loaded_SVMrbf_model)

SVC(gamma=0.7)


In [43]:
loaded_SVMrbf_model.predict(tfidf)

array([2])